# Generated by Django 5.2.4 on 2025-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedItem',
        ),
    ]
